fix: better nvim code assist (#88)
* ✨ remove ipv6 localhost warning

* 📝 tweak readme

* 🐛 set homebrew path during startup

* 📝 Indicate that dotme need to be restarted after fish shell set up

* ✨ remove persistent-apps from mac tool bar

* ✨ install brave browser

* ✨ better SSH key set up

* 📝 state complete after start

* ✨ move fish shell swap to final

* 🐛 correct variable name so can be used later

* 📝 indicate email address used in commits

* ✨ change fish shell in final

* 📦️ add uv python package manager

* 📦️ update packages

* 📦️ update lazy packages

* 📦️ update packages

* 🐛 finalise with should-run done

* ⚗️ exploring latex UX

* 📦️ Add fswatch

* 📦️ update lazy packages

* fix: yaml and markdown editing tweaks

* fix: more zen zen mode

* fix: stop vertical jitter on scroll

see https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/430

* fix: enabled autoformat on by default

* fix: update lazy plugins

* fix: add '` for surround with block

* fix: super-tab (with work around)

* fix: remove spurious echo X

* fix: upgrade packages

* fix: ignore some file extensions in telescope

* fix: use rg ignore file for ignores

* fix: add codecompanion with ollama

* fix: gemini agent support in code companion

* fix: re-enable support for pyenv

* chore package updates

diff --git a/bin/dotme-fish b/bin/dotme-fish
--- a/bin/dotme-fish
+++ b/bin/dotme-fish
@@ -7,19 +7,11 @@ should-run -m 7 $argv dotme-fish || exit 0
 
 printf "\e[36mConfiguring fish shell\e[0m\n"
 
-if not grep -q "/fish" /etc/shells
-  echo "! Please add "(which fish)" to /etc/shells"
-  echo "! You'll need to enter your password for this"
-  echo "! echo "(which fish)" | sudo tee -a /etc/shells"
-  echo "! chsh -s "(which fish)
-  exit 1
-end
-
 function fish_remove_path
-  if set -l index (contains -i "$argv" $fish_user_paths)
-    printf "\e[36mRemoving $argv from PATH\e[0m\n"
-    set -e fish_user_paths[$index]
-  end
+    if set -l index (contains -i "$argv" $fish_user_paths)
+        printf "\e[36mRemoving $argv from PATH\e[0m\n"
+        set -e fish_user_paths[$index]
+    end
 end
 
 #
@@ -30,7 +22,6 @@ end
 #
 #
 
-
 # See https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
 # fish_add_path ~/.npm-global/bin
 
@@ -39,34 +30,37 @@ set python_version 3.12
 
 echo $PATH
 
+set -Ux PYENV_ROOT $HOME/.pyenv
+
 fish_add_path ~/bin
+fish_add_path ~/.local/bin
 fish_add_path ~/.jenv/shims
 fish_add_path ~/.dotfiles/bin
-fish_add_path ~/.local/share/venv/bin
-fish_add_path ~/.pyenv/bin
 fish_add_path ~/.jenv/bin
 fish_add_path ~/.cargo/bin
 fish_add_path ~/.rbenv/shims
+fish_add_path $PYENV_ROOT/bin
 if is-silicon
-  fish_add_path /opt/homebrew/bin
-  fish_add_path /opt/homebrew/sbin
-  # Clean up legacy way of setting python path
-  set global_python_bin /opt/homebrew/opt/python@{$python_version}
-  fish_remove_path $global_python_bin
-  set local_python_bin /Users/ian/Library/Python/{$python_version}/bin
-  fish_remove_path $local_python_bin
-  fish_remove_path /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin
-  fish_remove_path /opt/homebrew/opt/python@3.10/libexec/bin
-  fish_remove_path /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin
+    fish_add_path /opt/homebrew/bin
+    fish_add_path /opt/homebrew/sbin
+    # Clean up legacy way of setting python path
+    set global_python_bin /opt/homebrew/opt/python@{$python_version}
+    fish_remove_path $global_python_bin
+    set local_python_bin /Users/ian/Library/Python/{$python_version}/bin
+    fish_remove_path $local_python_bin
+    fish_remove_path /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin
+    fish_remove_path /opt/homebrew/opt/python@3.10/libexec/bin
+    fish_remove_path /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin
 
 else
-  fish_remove_path /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin
+    fish_remove_path /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin
 end
 
 # Legacy clean up
 fish_remove_path ~/bin
 fish_remove_path ~/Library/Python/3.9/bin
 fish_remove_path ~/.local/share/venv
+fish_remove_path ~/.local/share/venv/bin
 
 # Google cloud
 fish_add_path ~/local/gcloud/google-cloud-sdk/bin
@@ -89,7 +83,7 @@ fish_add_path ~/Library/Android/sdk/platform-tools
 # Link in docker completions
 set dockerCompletions ~/.config/fish/completions/docker.fish
 if not test -L $dockerCompletions
-  ln -s /Applications/Docker.app/Contents/Resources/etc/docker.fish-completion $dockerCompletions
+    ln -s /Applications/Docker.app/Contents/Resources/etc/docker.fish-completion $dockerCompletions
 end
 
 set -U fish_greeting ""
