build : update versions

diff --git a/bin/dotme-brew b/bin/dotme-brew
--- a/bin/dotme-brew
+++ b/bin/dotme-brew
@@ -73,7 +73,7 @@ if [[ "$ADMIN" == "y" ]] ; then
 fi
 
 # Force pnpm overwrite, we'll always take an upgrade
-brew link --overwrite pnpm
+# brew link --overwrite pnpm
 
 # Restart Alfred - it might have updated, and it's quick to recycle, so until I
 # can be cleverer about restarting when updated ...
@@ -81,7 +81,7 @@ osascript -e 'tell application "Alfred" to quit'
 /usr/bin/open -a "Alfred 4" || echo "Cannot open Alfred"
 
 if [[ ! -d ~/.cache/vale ]] ; then
-  vale sync
+  vale sync || echo "failed to sync vale"
 fi
 
 should-run -fu $0
