dap ; pnpm global (#53)

diff --git a/bin/dotme-node b/bin/dotme-node
--- a/bin/dotme-node
+++ b/bin/dotme-node
@@ -10,30 +10,49 @@
 #
 
 NODE_GLOBAL=~/.dotfiles/config/node/global.txt
-should-run -m 14 $0 $NODE_GLOBAL || exit 0
+should-run -m 14 $@ $0 $NODE_GLOBAL || exit 0
+$(shim) && . ${ME}/i.sh
 
 #
 # Set up nvm
 #
 [ ! -d ~/.nvm ] && mkdir ~/.nvm
 
+
+#
+# Node is installed with brew and pnpm installed with corepack
+#
 which node
 node -v
 
 #
-# Report what's install globally
+# Uninstall all npm globals so that we can use pnpm
 #
-npm list --global --depth=0
+
+log:: "Cleaning npm globals"
+npm ls --global --json                                                 |
+  jq --raw-output  '.dependencies | keys[] | select(. != "npm")' |
+  xargs -r npm -g rm
+
+log:: "Updating pnpm"
+#
+# pnpm needs one package to be able start listing globals
+#
+log:: "pnpm global list"
+pnpm --global list 2>/dev/null || pnpm --global install pyright
 
 # Install missing packages
 
-cat $NODE_GLOBAL | grep -v '#' | grep '@' |
-  grep -F -v "`npm list --global --depth=0 2>/dev/null | grep "@" |
-  sed 's/.* \(.*\)@[^@]*/\1@/'`" |
-  xargs npm install --global
+log:: "pnpm install missing global"
+cat $NODE_GLOBAL | grep -v '#' | grep '@'          |
+  grep -F -v "`pnpm --global --json list           |
+    jq --raw-output '.[0].dependencies | keys[]'`" |
+  xargs pnpm install --global
 
-npm -g outdated
-npm -g update
+log:: "pnpm outdated"
+pnpm --global outdated
+# log:: "pnpm update"
+# pnpm -g update
 
 echo
 echo "... Global node packages installed"
