Improve git-synk to support child directories

diff --git a/bin/git-synk b/bin/git-synk
--- a/bin/git-synk
+++ b/bin/git-synk
@@ -30,7 +30,7 @@ esac done
 
 #
 # Execute git quietly ... keybase output messages in stderr
-# this function safely removes these known errors, but 
+# this function safely removes these known errors, but
 # keeps unknown errors
 #
 function gitQuiet() {
@@ -49,7 +49,7 @@ function gitQuiet() {
 function gitSynk() {
   # Make sure in git repository
   git rev-parse
-  
+
   fullBranchName=$(git symbolic-ref -q HEAD)
   branchName=${fullBranchName##refs/heads/}
   originUrl=$(git config --get remote.origin.url)
@@ -63,8 +63,9 @@ function gitSynk() {
       # Handle dirty state only if autocommit flag set
       git add -A ; git commit --quiet -m "sync"
     else
-      echo "Cannot sync - local changes and autocommit not set"
-      exit 128
+      current=`pwd`
+      echo "Cannot sync ${current##*/} - local changes and autocommit not set"
+      return 128
     fi
   fi
 
@@ -102,7 +103,24 @@ function gitSynk() {
     printf " ↑"
     gitQuiet "push"
   fi
+  printf " ☆"
 }
 
-gitSynk
-printf " ☆"
+if git rev-parse 2>/dev/null  ; then
+  gitSynk || exit 128
+else
+  current=`pwd`
+  first=1
+  error=0
+  for child in */ ; do
+   cd ${current}
+   if [ -d "${child}.git" ] ; then
+     [[ first -eq 0 ]] && printf "\n"
+     cd $child
+     gitSynk || error=1
+     first=0
+   fi
+  done
+  [[ $error -eq 0 ]] || exit $error
+fi
+
