git batch process

diff --git a/bin/git-batch b/bin/git-batch
--- a/bin/git-batch
+++ b/bin/git-batch
@@ -16,11 +16,35 @@
 
 $(shim) && . ${ME}/i.sh
 
+help() {
+  cat << EOF
+
+Batch git changes
+
+  -h this help
+  -t use time in batch name
+  -n explicit batch name
+
+Create a new batch
+
+  git batch
+
+Complete a batch
+
+  git batch complete
+
+EOF
+}
+
 OPTIND=1
-while getopts "hn:" o; do case "$o" in
-  h) WITH_HOUR="y" ;;
+while getopts "hn:t" o; do case "$o" in
+  h) help && exit 0 ;;
+  t) WITH_TIME="y" ;;
   n) BATCH_NAME=$OPTARG ;;
 esac done
+shift $((OPTIND-1))
+
+COMMAND=$1
 
 trunk=main
 
@@ -29,11 +53,10 @@ function newBatch {
   if [[ "$currentBranchName" != "$trunk" ]] ; then
     log::error "On $currentBranchName"
   else
-    log::info "Creating a new batch"
     if [ -n "$BATCH_NAME" ] ; then
       batchName=$BATCH_NAME
-    elif [ "$WITH_HOUR" == "y" ] ; then
-      batchName=`date +%Y%m%d%H`
+    elif [ "$WITH_TIME" == "y" ] ; then
+      batchName=`date +%Y%m%d%H%M`
     else
       batchName=`date +%Y%m%d`
     fi
@@ -53,7 +76,36 @@ function newBatch {
   git ls-remote --heads origin | grep "/batch/"
 }
 
-newBatch
+function completeBatch {
+  currentBranchName=`git rev-parse --abbrev-ref HEAD`
+  if [[ "${currentBranchName}" != batch/* ]] ; then
+    log::error "Current branch ${currentBranchName} is not a batch"
+  else
+    git commit -am "batch complete"
+    # early push in case issues, however on success remote
+    # branch will be removed
+    git push
+    # Sequash merge onto trunk with auto commit message. If there
+    # are comflicts then this will fail and the conflict should be resolved 
+    # manually
+    git checkout $trunk
+    git merge --squash $currentBranchName
+    git commit -m "${currentBranchName}"
+    git push
+    # auto delete remote bracnh, not that local copy remains
+    # and is useful for troubleshooting
+    git push origin -d "${currentBranchName}"
+  fi
+}
+
+if [[ -z "$COMMAND" ]] ; then
+  newBatch
+elif [[ "$COMMAND" == "complete" ]] ; then
+  set -e
+  completeBatch
+else
+  echo "Command $COMMAND" is not recognised
+fi
 
 
 
